substitutions:
  device_name: smart-bed
  friendly_name: Smart Bed
  location: My Room

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:
captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Ota (over the air updates)
ota:
  password: !secret ota_password

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret recovery_ap_password

# Output Config
output:
  - platform: gpio
    pin: GPIO23
    id: wifi_status_led
  - platform: gpio
    pin: GPIO32
    id: relay_head_up_pin
  - platform: gpio
    pin: GPIO33
    id: relay_head_down_pin
  - platform: gpio
    pin: GPIO25
    id: relay_legs_up_pin
  - platform: gpio
    pin: GPIO26
    id: relay_legs_down_pin

# Define the switches based on the relay pins
switch:
  - platform: output
    id: head_up
    name: "Head Up"
    output: relay_head_up_pin
  - platform: output
    id: head_down
    name: "Head Down"
    output: relay_head_down_pin
  - platform: output
    id: legs_up
    name: "Legs Up"
    output: relay_legs_up_pin
  - platform: output
    id: legs_down
    name: "Legs Down"
    output: relay_legs_down_pin

# Check the wifi status and turn on/off the wifi status LED
interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - output.turn_on: wifi_status_led
        else:
          - output.turn_off: wifi_status_led